repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: jekyll-build
        name: Build Jekyll site
        entry: env JEKYLL_NO_BUNDLER_REQUIRE=true jekyll build --trace
        language: ruby
        language_version: 3.2.2
        additional_dependencies: [github-pages:231]
        pass_filenames: false
        always_run: true
